version: '2.1'
services:
    jenkins:
        build: ./jenkins
        ports:
            - "8080:8080"
            - "50000:50000"
        networks:
            - sonarnet
    sonar:
        image: sonarqube
        ports:
            - "9000:9000"
        networks:
            - sonarnet
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    db:
        image: postgres
        networks:
            - sonarnet
        environment:
            - POSTGRES_USER=sonar
            - POSTGRES_PASSWORD=sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data
networks:
    sonarnet:
        driver: bridge

volumes:
    sonarqube_conf:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_bundled-plugins:
    postgresql:
    postgresql_data:
